apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  type: ClusterIP
  ports:
    - name: service1
      protocol: TCP
      port: 3000
      targetPort: 3000
