apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  selector:
    app: service2
  type: ClusterIP
  ports:
    - name: service2
      protocol: TCP
      port: 3000
      targetPort: 3000
